# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.btn_dir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_dir.setObjectName("btn_dir")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(190, 470, 111, 31))
        self.btn_left.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_left.setObjectName("btn_left")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 161, 471))
        self.listWidget.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(216, 62, 521, 391))
        self.label.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(310, 470, 111, 31))
        self.btn_right.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_right.setObjectName("btn_right")
        self.btn_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_flip.setGeometry(QtCore.QRect(430, 470, 111, 31))
        self.btn_flip.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_flip.setObjectName("btn_flip")
        self.btn_sharp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sharp.setGeometry(QtCore.QRect(560, 470, 111, 31))
        self.btn_sharp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_sharp.setObjectName("btn_sharp")
        self.QPushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.QPushButton_6.setGeometry(QtCore.QRect(680, 470, 111, 31))
        self.QPushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.QPushButton_6.setObjectName("QPushButton_6")
        self.btn_left_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left_2.setGeometry(QtCore.QRect(680, 510, 111, 31))
        self.btn_left_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 136, 136);\n"
"border-radius: 10px;")
        self.btn_left_2.setObjectName("btn_left_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_dir.setText(_translate("MainWindow", "Папка "))
        self.btn_left.setText(_translate("MainWindow", "Вліво"))
        self.btn_right.setText(_translate("MainWindow", "Вправо"))
        self.btn_flip.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.QPushButton_6.setText(_translate("MainWindow", "Ч/Б"))
        self.btn_left_2.setText(_translate("MainWindow", "Зберегти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
