# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 571, 691))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(630, 30, 91, 31))
        self.label.setObjectName("label")
        self.list_1 = QtWidgets.QListWidget(self.centralwidget)
        self.list_1.setGeometry(QtCore.QRect(630, 70, 331, 192))
        self.list_1.setObjectName("list_1")
        self.btn_make = QtWidgets.QPushButton(self.centralwidget)
        self.btn_make.setGeometry(QtCore.QRect(640, 280, 121, 31))
        self.btn_make.setObjectName("btn_make")
        self.bnt_delete = QtWidgets.QPushButton(self.centralwidget)
        self.bnt_delete.setGeometry(QtCore.QRect(830, 280, 121, 31))
        self.bnt_delete.setObjectName("bnt_delete")
        self.bnt_save = QtWidgets.QPushButton(self.centralwidget)
        self.bnt_save.setGeometry(QtCore.QRect(640, 320, 311, 31))
        self.bnt_save.setObjectName("bnt_save")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 370, 101, 51))
        self.label_2.setObjectName("label_2")
        self.btn_detach = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detach.setGeometry(QtCore.QRect(830, 670, 121, 31))
        self.btn_detach.setObjectName("btn_detach")
        self.list_2 = QtWidgets.QListWidget(self.centralwidget)
        self.list_2.setGeometry(QtCore.QRect(630, 430, 331, 192))
        self.list_2.setObjectName("list_2")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(630, 710, 321, 31))
        self.btn_search.setObjectName("btn_search")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(630, 670, 121, 31))
        self.btn_add.setObjectName("btn_add")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(632, 629, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ТЕКСТ....</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "СПИСОК ЗАМІТО"))
        self.btn_make.setText(_translate("MainWindow", "Створити замітку"))
        self.bnt_delete.setText(_translate("MainWindow", "Видалити замітку"))
        self.bnt_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.label_2.setText(_translate("MainWindow", "СПИСОК ТЕГІВ"))
        self.btn_detach.setText(_translate("MainWindow", "Відкріпити замітк "))
        self.btn_search.setText(_translate("MainWindow", "Шукати замітку по тегу"))
        self.btn_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.lineEdit.setText(_translate("MainWindow", "Ведіть тег..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
